/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Backup;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackupRecord extends UpdatableRecordImpl<BackupRecord> implements Record5<Integer, String, String, String, Timestamp> {

	private static final long serialVersionUID = 623615242;

	/**
	 * Setter for <code>PUBLIC.BACKUP.IDBACKUP</code>.
	 */
	public void setIdbackup(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.BACKUP.IDBACKUP</code>.
	 */
	public Integer getIdbackup() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.BACKUP.FILEPATH</code>.
	 */
	public void setFilepath(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.BACKUP.FILEPATH</code>.
	 */
	public String getFilepath() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.BACKUP.FILENAME</code>.
	 */
	public void setFilename(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.BACKUP.FILENAME</code>.
	 */
	public String getFilename() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.BACKUP.SERVICENAME</code>.
	 */
	public void setServicename(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.BACKUP.SERVICENAME</code>.
	 */
	public String getServicename() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.BACKUP.LASTATTEMPT</code>.
	 */
	public void setLastattempt(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.BACKUP.LASTATTEMPT</code>.
	 */
	public Timestamp getLastattempt() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Backup.BACKUP.IDBACKUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Backup.BACKUP.FILEPATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Backup.BACKUP.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Backup.BACKUP.SERVICENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Backup.BACKUP.LASTATTEMPT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdbackup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFilepath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getServicename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getLastattempt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupRecord value1(Integer value) {
		setIdbackup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupRecord value2(String value) {
		setFilepath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupRecord value3(String value) {
		setFilename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupRecord value4(String value) {
		setServicename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupRecord value5(Timestamp value) {
		setLastattempt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BackupRecord
	 */
	public BackupRecord() {
		super(Backup.BACKUP);
	}

	/**
	 * Create a detached, initialised BackupRecord
	 */
	public BackupRecord(Integer idbackup, String filepath, String filename, String servicename, Timestamp lastattempt) {
		super(Backup.BACKUP);

		setValue(0, idbackup);
		setValue(1, filepath);
		setValue(2, filename);
		setValue(3, servicename);
		setValue(4, lastattempt);
	}
}
