/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record21;
import org.jooq.Record4;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Chlorinecalculation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChlorinecalculationRecord extends UpdatableRecordImpl<ChlorinecalculationRecord> implements Record21<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, String, Double, Double, Double, Double, Double, Double, Double, Double, Double> {

	private static final long serialVersionUID = 1269250539;

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.DATE</code>. INPUT
	 */
	public void setDate(Timestamp value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.DATE</code>. INPUT
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_IDWATERSYSTEM</code>. INPUT
	 */
	public void setWatersystemIdwatersystem(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_IDWATERSYSTEM</code>. INPUT
	 */
	public Integer getWatersystemIdwatersystem() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>. INPUT
	 */
	public void setWatersystemCommunityIdcommunity(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>. INPUT
	 */
	public Integer getWatersystemCommunityIdcommunity() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>. INPUT
	 */
	public void setWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>. INPUT
	 */
	public Integer getWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.FAMILIESNUM</code>. INPUT
	 */
	public void setFamiliesnum(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.FAMILIESNUM</code>. INPUT
	 */
	public Integer getFamiliesnum() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.POPULATION</code>. INPUT
	 */
	public void setPopulation(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.POPULATION</code>. INPUT
	 */
	public Integer getPopulation() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.TANKVOLUME</code>. INPUT
	 */
	public void setTankvolume(Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.TANKVOLUME</code>. INPUT
	 */
	public Double getTankvolume() {
		return (Double) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.ENDOWMENT</code>. INPUT
	 */
	public void setEndowment(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.ENDOWMENT</code>. INPUT
	 */
	public Double getEndowment() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEPURENESS</code>. INPUT
	 */
	public void setChlorinepureness(Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEPURENESS</code>. INPUT
	 */
	public Double getChlorinepureness() {
		return (Double) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.NATURALFLOW</code>. INPUT
	 */
	public void setNaturalflow(Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.NATURALFLOW</code>. INPUT
	 */
	public Double getNaturalflow() {
		return (Double) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINATEDFLOW</code>. INPUT
	 */
	public void setChlorinatedflow(Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINATEDFLOW</code>. INPUT
	 */
	public Double getChlorinatedflow() {
		return (Double) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINETYPE</code>. INPUT
	 */
	public void setChlorinetype(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINETYPE</code>. INPUT
	 */
	public String getChlorinetype() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.DRIPPINGHOURSPERDAY</code>. INPUT
	 */
	public void setDrippinghoursperday(Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.DRIPPINGHOURSPERDAY</code>. INPUT
	 */
	public Double getDrippinghoursperday() {
		return (Double) getValue(12);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEDEMAND</code>. INPUT
	 */
	public void setChlorinedemand(Double value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEDEMAND</code>. INPUT
	 */
	public Double getChlorinedemand() {
		return (Double) getValue(13);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEPRICE</code>. INPUT
	 */
	public void setChlorineprice(Double value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEPRICE</code>. INPUT
	 */
	public Double getChlorineprice() {
		return (Double) getValue(14);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.RELOADTIME</code>. INPUT
	 */
	public void setReloadtime(Double value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.RELOADTIME</code>. INPUT
	 */
	public Double getReloadtime() {
		return (Double) getValue(15);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEDOSEPERFORTNIGHT</code>. RESULT
	 */
	public void setChlorinedoseperfortnight(Double value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEDOSEPERFORTNIGHT</code>. RESULT
	 */
	public Double getChlorinedoseperfortnight() {
		return (Double) getValue(16);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEDOSEPERMONTH</code>. RESULT
	 */
	public void setChlorinedosepermonth(Double value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINEDOSEPERMONTH</code>. RESULT
	 */
	public Double getChlorinedosepermonth() {
		return (Double) getValue(17);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.DRIPPINGFLOWINML</code>. RESULT
	 */
	public void setDrippingflowinml(Double value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.DRIPPINGFLOWINML</code>. RESULT
	 */
	public Double getDrippingflowinml() {
		return (Double) getValue(18);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.DRIPPINGFLOWINDROPS</code>. RESULT
	 */
	public void setDrippingflowindrops(Double value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.DRIPPINGFLOWINDROPS</code>. RESULT
	 */
	public Double getDrippingflowindrops() {
		return (Double) getValue(19);
	}

	/**
	 * Setter for <code>PUBLIC.CHLORINECALCULATION.CHLORINATIONCOST</code>. RESULT
	 */
	public void setChlorinationcost(Double value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>PUBLIC.CHLORINECALCULATION.CHLORINATIONCOST</code>. RESULT
	 */
	public Double getChlorinationcost() {
		return (Double) getValue(20);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record4<Timestamp, Integer, Integer, Integer> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record21 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row21<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, String, Double, Double, Double, Double, Double, Double, Double, Double, Double> fieldsRow() {
		return (Row21) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row21<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, String, Double, Double, Double, Double, Double, Double, Double, Double, Double> valuesRow() {
		return (Row21) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field1() {
		return Chlorinecalculation.CHLORINECALCULATION.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Chlorinecalculation.CHLORINECALCULATION.FAMILIESNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Chlorinecalculation.CHLORINECALCULATION.POPULATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field7() {
		return Chlorinecalculation.CHLORINECALCULATION.TANKVOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Chlorinecalculation.CHLORINECALCULATION.ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field9() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINEPURENESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field10() {
		return Chlorinecalculation.CHLORINECALCULATION.NATURALFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field11() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINATEDFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINETYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field13() {
		return Chlorinecalculation.CHLORINECALCULATION.DRIPPINGHOURSPERDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field14() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINEDEMAND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field15() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINEPRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field16() {
		return Chlorinecalculation.CHLORINECALCULATION.RELOADTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field17() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINEDOSEPERFORTNIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field18() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINEDOSEPERMONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field19() {
		return Chlorinecalculation.CHLORINECALCULATION.DRIPPINGFLOWINML;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field20() {
		return Chlorinecalculation.CHLORINECALCULATION.DRIPPINGFLOWINDROPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field21() {
		return Chlorinecalculation.CHLORINECALCULATION.CHLORINATIONCOST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value1() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getFamiliesnum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPopulation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value7() {
		return getTankvolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value9() {
		return getChlorinepureness();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value10() {
		return getNaturalflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value11() {
		return getChlorinatedflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getChlorinetype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value13() {
		return getDrippinghoursperday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value14() {
		return getChlorinedemand();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value15() {
		return getChlorineprice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value16() {
		return getReloadtime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value17() {
		return getChlorinedoseperfortnight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value18() {
		return getChlorinedosepermonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value19() {
		return getDrippingflowinml();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value20() {
		return getDrippingflowindrops();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value21() {
		return getChlorinationcost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value1(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value2(Integer value) {
		setWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value3(Integer value) {
		setWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value4(Integer value) {
		setWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value5(Integer value) {
		setFamiliesnum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value6(Integer value) {
		setPopulation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value7(Double value) {
		setTankvolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value8(Double value) {
		setEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value9(Double value) {
		setChlorinepureness(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value10(Double value) {
		setNaturalflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value11(Double value) {
		setChlorinatedflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value12(String value) {
		setChlorinetype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value13(Double value) {
		setDrippinghoursperday(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value14(Double value) {
		setChlorinedemand(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value15(Double value) {
		setChlorineprice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value16(Double value) {
		setReloadtime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value17(Double value) {
		setChlorinedoseperfortnight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value18(Double value) {
		setChlorinedosepermonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value19(Double value) {
		setDrippingflowinml(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value20(Double value) {
		setDrippingflowindrops(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord value21(Double value) {
		setChlorinationcost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChlorinecalculationRecord values(Timestamp value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Double value7, Double value8, Double value9, Double value10, Double value11, String value12, Double value13, Double value14, Double value15, Double value16, Double value17, Double value18, Double value19, Double value20, Double value21) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		value20(value20);
		value21(value21);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChlorinecalculationRecord
	 */
	public ChlorinecalculationRecord() {
		super(Chlorinecalculation.CHLORINECALCULATION);
	}

	/**
	 * Create a detached, initialised ChlorinecalculationRecord
	 */
	public ChlorinecalculationRecord(Timestamp date, Integer watersystemIdwatersystem, Integer watersystemCommunityIdcommunity, Integer watersystemCommunitySubbasinIdsubbasin, Integer familiesnum, Integer population, Double tankvolume, Double endowment, Double chlorinepureness, Double naturalflow, Double chlorinatedflow, String chlorinetype, Double drippinghoursperday, Double chlorinedemand, Double chlorineprice, Double reloadtime, Double chlorinedoseperfortnight, Double chlorinedosepermonth, Double drippingflowinml, Double drippingflowindrops, Double chlorinationcost) {
		super(Chlorinecalculation.CHLORINECALCULATION);

		setValue(0, date);
		setValue(1, watersystemIdwatersystem);
		setValue(2, watersystemCommunityIdcommunity);
		setValue(3, watersystemCommunitySubbasinIdsubbasin);
		setValue(4, familiesnum);
		setValue(5, population);
		setValue(6, tankvolume);
		setValue(7, endowment);
		setValue(8, chlorinepureness);
		setValue(9, naturalflow);
		setValue(10, chlorinatedflow);
		setValue(11, chlorinetype);
		setValue(12, drippinghoursperday);
		setValue(13, chlorinedemand);
		setValue(14, chlorineprice);
		setValue(15, reloadtime);
		setValue(16, chlorinedoseperfortnight);
		setValue(17, chlorinedosepermonth);
		setValue(18, drippingflowinml);
		setValue(19, drippingflowindrops);
		setValue(20, chlorinationcost);
	}
}
