/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Community;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommunityRecord extends UpdatableRecordImpl<CommunityRecord> implements Record3<Integer, Integer, String> {

	private static final long serialVersionUID = 177232974;

	/**
	 * Setter for <code>PUBLIC.COMMUNITY.IDCOMMUNITY</code>.
	 */
	public void setIdcommunity(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMUNITY.IDCOMMUNITY</code>.
	 */
	public Integer getIdcommunity() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.COMMUNITY.SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setSubbasinIdsubbasin(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMUNITY.SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getSubbasinIdsubbasin() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.COMMUNITY.NAME</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMMUNITY.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Community.COMMUNITY.IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Community.COMMUNITY.SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Community.COMMUNITY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommunityRecord value1(Integer value) {
		setIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommunityRecord value2(Integer value) {
		setSubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommunityRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommunityRecord values(Integer value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CommunityRecord
	 */
	public CommunityRecord() {
		super(Community.COMMUNITY);
	}

	/**
	 * Create a detached, initialised CommunityRecord
	 */
	public CommunityRecord(Integer idcommunity, Integer subbasinIdsubbasin, String name) {
		super(Community.COMMUNITY);

		setValue(0, idcommunity);
		setValue(1, subbasinIdsubbasin);
		setValue(2, name);
	}
}
