/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record4;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Cubicreservoir;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CubicreservoirRecord extends UpdatableRecordImpl<CubicreservoirRecord> implements Record10<Integer, Integer, Integer, Integer, String, Double, Double, Double, Integer, Double> {

	private static final long serialVersionUID = 1306585180;

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.IDCUBICRESERVOIR</code>.
	 */
	public void setIdcubicreservoir(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.IDCUBICRESERVOIR</code>.
	 */
	public Integer getIdcubicreservoir() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public void setWatersystemIdwatersystem(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public Integer getWatersystemIdwatersystem() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setWatersystemCommunityIdcommunity(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getWatersystemCommunityIdcommunity() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.NAME</code>.
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.WIDTH</code>.
	 */
	public void setWidth(Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.WIDTH</code>.
	 */
	public Double getWidth() {
		return (Double) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.LENGTH</code>.
	 */
	public void setLength(Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.LENGTH</code>.
	 */
	public Double getLength() {
		return (Double) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.HEIGHT</code>.
	 */
	public void setHeight(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.HEIGHT</code>.
	 */
	public Double getHeight() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.COUNT</code>.
	 */
	public void setCount(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.COUNT</code>.
	 */
	public Integer getCount() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.CUBICRESERVOIR.REQUIREDCONCENTRATION</code>.
	 */
	public void setRequiredconcentration(Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUBICRESERVOIR.REQUIREDCONCENTRATION</code>.
	 */
	public Double getRequiredconcentration() {
		return (Double) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record4<Integer, Integer, Integer, Integer> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, Integer, Integer, String, Double, Double, Double, Integer, Double> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, Integer, Integer, String, Double, Double, Double, Integer, Double> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Cubicreservoir.CUBICRESERVOIR.IDCUBICRESERVOIR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Cubicreservoir.CUBICRESERVOIR.WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Cubicreservoir.CUBICRESERVOIR.WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Cubicreservoir.CUBICRESERVOIR.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Cubicreservoir.CUBICRESERVOIR.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field6() {
		return Cubicreservoir.CUBICRESERVOIR.WIDTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field7() {
		return Cubicreservoir.CUBICRESERVOIR.LENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Cubicreservoir.CUBICRESERVOIR.HEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Cubicreservoir.CUBICRESERVOIR.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field10() {
		return Cubicreservoir.CUBICRESERVOIR.REQUIREDCONCENTRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdcubicreservoir();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value6() {
		return getWidth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value7() {
		return getLength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getHeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value10() {
		return getRequiredconcentration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value1(Integer value) {
		setIdcubicreservoir(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value2(Integer value) {
		setWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value3(Integer value) {
		setWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value4(Integer value) {
		setWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value6(Double value) {
		setWidth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value7(Double value) {
		setLength(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value8(Double value) {
		setHeight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value9(Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord value10(Double value) {
		setRequiredconcentration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CubicreservoirRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, Double value6, Double value7, Double value8, Integer value9, Double value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CubicreservoirRecord
	 */
	public CubicreservoirRecord() {
		super(Cubicreservoir.CUBICRESERVOIR);
	}

	/**
	 * Create a detached, initialised CubicreservoirRecord
	 */
	public CubicreservoirRecord(Integer idcubicreservoir, Integer watersystemIdwatersystem, Integer watersystemCommunityIdcommunity, Integer watersystemCommunitySubbasinIdsubbasin, String name, Double width, Double length, Double height, Integer count, Double requiredconcentration) {
		super(Cubicreservoir.CUBICRESERVOIR);

		setValue(0, idcubicreservoir);
		setValue(1, watersystemIdwatersystem);
		setValue(2, watersystemCommunityIdcommunity);
		setValue(3, watersystemCommunitySubbasinIdsubbasin);
		setValue(4, name);
		setValue(5, width);
		setValue(6, length);
		setValue(7, height);
		setValue(8, count);
		setValue(9, requiredconcentration);
	}
}
