/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuredflow;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasuredflowRecord extends UpdatableRecordImpl<MeasuredflowRecord> implements Record8<Timestamp, Integer, Integer, Integer, Integer, Integer, Byte, String> {

	private static final long serialVersionUID = 85863362;

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.DATE</code>.
	 */
	public void setDate(Timestamp value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.DATE</code>.
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_IDMEASURINGPOINT</code>.
	 */
	public void setMeasuringpointIdmeasuringpoint(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_IDMEASURINGPOINT</code>.
	 */
	public Integer getMeasuringpointIdmeasuringpoint() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public void setMeasuringpointWatersystemHasWaterspringWatersystemIdwatersystem(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public Integer getMeasuringpointWatersystemHasWaterspringWatersystemIdwatersystem() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setMeasuringpointWatersystemHasWaterspringWatersystemCommunityIdcommunity(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getMeasuringpointWatersystemHasWaterspringWatersystemCommunityIdcommunity() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setMeasuringpointWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getMeasuringpointWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING</code>.
	 */
	public void setMeasuringpointWatersystemHasWaterspringWaterspringIdwaterspring(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING</code>.
	 */
	public Integer getMeasuringpointWatersystemHasWaterspringWaterspringIdwaterspring() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.FLOW</code>.
	 */
	public void setFlow(Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.FLOW</code>.
	 */
	public Byte getFlow() {
		return (Byte) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.MEASUREDFLOW.COMMENTS</code>.
	 */
	public void setComments(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASUREDFLOW.COMMENTS</code>.
	 */
	public String getComments() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record6<Timestamp, Integer, Integer, Integer, Integer, Integer> key() {
		return (Record6) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Timestamp, Integer, Integer, Integer, Integer, Integer, Byte, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Timestamp, Integer, Integer, Integer, Integer, Integer, Byte, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field1() {
		return Measuredflow.MEASUREDFLOW.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Measuredflow.MEASUREDFLOW.MEASURINGPOINT_IDMEASURINGPOINT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field7() {
		return Measuredflow.MEASUREDFLOW.FLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Measuredflow.MEASUREDFLOW.COMMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value1() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getMeasuringpointIdmeasuringpoint();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getMeasuringpointWatersystemHasWaterspringWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getMeasuringpointWatersystemHasWaterspringWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getMeasuringpointWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getMeasuringpointWatersystemHasWaterspringWaterspringIdwaterspring();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value7() {
		return getFlow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getComments();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value1(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value2(Integer value) {
		setMeasuringpointIdmeasuringpoint(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value3(Integer value) {
		setMeasuringpointWatersystemHasWaterspringWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value4(Integer value) {
		setMeasuringpointWatersystemHasWaterspringWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value5(Integer value) {
		setMeasuringpointWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value6(Integer value) {
		setMeasuringpointWatersystemHasWaterspringWaterspringIdwaterspring(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value7(Byte value) {
		setFlow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord value8(String value) {
		setComments(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuredflowRecord values(Timestamp value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Byte value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MeasuredflowRecord
	 */
	public MeasuredflowRecord() {
		super(Measuredflow.MEASUREDFLOW);
	}

	/**
	 * Create a detached, initialised MeasuredflowRecord
	 */
	public MeasuredflowRecord(Timestamp date, Integer measuringpointIdmeasuringpoint, Integer measuringpointWatersystemHasWaterspringWatersystemIdwatersystem, Integer measuringpointWatersystemHasWaterspringWatersystemCommunityIdcommunity, Integer measuringpointWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin, Integer measuringpointWatersystemHasWaterspringWaterspringIdwaterspring, Byte flow, String comments) {
		super(Measuredflow.MEASUREDFLOW);

		setValue(0, date);
		setValue(1, measuringpointIdmeasuringpoint);
		setValue(2, measuringpointWatersystemHasWaterspringWatersystemIdwatersystem);
		setValue(3, measuringpointWatersystemHasWaterspringWatersystemCommunityIdcommunity);
		setValue(4, measuringpointWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin);
		setValue(5, measuringpointWatersystemHasWaterspringWaterspringIdwaterspring);
		setValue(6, flow);
		setValue(7, comments);
	}
}
