/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuringpoint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasuringpointRecord extends UpdatableRecordImpl<MeasuringpointRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, String> {

	private static final long serialVersionUID = 978996663;

	/**
	 * Setter for <code>PUBLIC.MEASURINGPOINT.IDMEASURINGPOINT</code>.
	 */
	public void setIdmeasuringpoint(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASURINGPOINT.IDMEASURINGPOINT</code>.
	 */
	public Integer getIdmeasuringpoint() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public void setWatersystemHasWaterspringWatersystemIdwatersystem(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public Integer getWatersystemHasWaterspringWatersystemIdwatersystem() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setWatersystemHasWaterspringWatersystemCommunityIdcommunity(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getWatersystemHasWaterspringWatersystemCommunityIdcommunity() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING</code>.
	 */
	public void setWatersystemHasWaterspringWaterspringIdwaterspring(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING</code>.
	 */
	public Integer getWatersystemHasWaterspringWaterspringIdwaterspring() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.MEASURINGPOINT.NAME</code>.
	 */
	public void setName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEASURINGPOINT.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record5<Integer, Integer, Integer, Integer, Integer> key() {
		return (Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Measuringpoint.MEASURINGPOINT.IDMEASURINGPOINT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Measuringpoint.MEASURINGPOINT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdmeasuringpoint();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getWatersystemHasWaterspringWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getWatersystemHasWaterspringWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getWatersystemHasWaterspringWaterspringIdwaterspring();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord value1(Integer value) {
		setIdmeasuringpoint(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord value2(Integer value) {
		setWatersystemHasWaterspringWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord value3(Integer value) {
		setWatersystemHasWaterspringWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord value4(Integer value) {
		setWatersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord value5(Integer value) {
		setWatersystemHasWaterspringWaterspringIdwaterspring(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord value6(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeasuringpointRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MeasuringpointRecord
	 */
	public MeasuringpointRecord() {
		super(Measuringpoint.MEASURINGPOINT);
	}

	/**
	 * Create a detached, initialised MeasuringpointRecord
	 */
	public MeasuringpointRecord(Integer idmeasuringpoint, Integer watersystemHasWaterspringWatersystemIdwatersystem, Integer watersystemHasWaterspringWatersystemCommunityIdcommunity, Integer watersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin, Integer watersystemHasWaterspringWaterspringIdwaterspring, String name) {
		super(Measuringpoint.MEASURINGPOINT);

		setValue(0, idmeasuringpoint);
		setValue(1, watersystemHasWaterspringWatersystemIdwatersystem);
		setValue(2, watersystemHasWaterspringWatersystemCommunityIdcommunity);
		setValue(3, watersystemHasWaterspringWatersystemCommunitySubbasinIdsubbasin);
		setValue(4, watersystemHasWaterspringWaterspringIdwaterspring);
		setValue(5, name);
	}
}
