/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Record5;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Pipedesinfection;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PipedesinfectionRecord extends UpdatableRecordImpl<PipedesinfectionRecord> implements Record12<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double> {

	private static final long serialVersionUID = 1206516882;

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.DATE</code>.
	 */
	public void setDate(Timestamp value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.DATE</code>.
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.PIPE_IDPIPE</code>.
	 */
	public void setPipeIdpipe(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.PIPE_IDPIPE</code>.
	 */
	public Integer getPipeIdpipe() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public void setPipeWatersystemIdwatersystem(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public Integer getPipeWatersystemIdwatersystem() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setPipeWatersystemCommunityIdcommunity(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getPipeWatersystemCommunityIdcommunity() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setPipeWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getPipeWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.COUNT</code>.
	 */
	public void setCount(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.COUNT</code>.
	 */
	public Integer getCount() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.VOLUME</code>.
	 */
	public void setVolume(Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.VOLUME</code>.
	 */
	public Double getVolume() {
		return (Double) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.CHLORINECONCENTRATION</code>.
	 */
	public void setChlorineconcentration(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.CHLORINECONCENTRATION</code>.
	 */
	public Double getChlorineconcentration() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.DEMANDACTIVECHLORINE</code>.
	 */
	public void setDemandactivechlorine(Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.DEMANDACTIVECHLORINE</code>.
	 */
	public Double getDemandactivechlorine() {
		return (Double) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.DEMAND70CHLORINE</code>.
	 */
	public void setDemand70chlorine(Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.DEMAND70CHLORINE</code>.
	 */
	public Double getDemand70chlorine() {
		return (Double) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.DEMANDSPOONS</code>.
	 */
	public void setDemandspoons(Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.DEMANDSPOONS</code>.
	 */
	public Double getDemandspoons() {
		return (Double) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.PIPEDESINFECTION.RETENTIONTIME</code>.
	 */
	public void setRetentiontime(Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.PIPEDESINFECTION.RETENTIONTIME</code>.
	 */
	public Double getRetentiontime() {
		return (Double) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record5<Timestamp, Integer, Integer, Integer, Integer> key() {
		return (Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field1() {
		return Pipedesinfection.PIPEDESINFECTION.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Pipedesinfection.PIPEDESINFECTION.PIPE_IDPIPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Pipedesinfection.PIPEDESINFECTION.PIPE_WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Pipedesinfection.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Pipedesinfection.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Pipedesinfection.PIPEDESINFECTION.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field7() {
		return Pipedesinfection.PIPEDESINFECTION.VOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Pipedesinfection.PIPEDESINFECTION.CHLORINECONCENTRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field9() {
		return Pipedesinfection.PIPEDESINFECTION.DEMANDACTIVECHLORINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field10() {
		return Pipedesinfection.PIPEDESINFECTION.DEMAND70CHLORINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field11() {
		return Pipedesinfection.PIPEDESINFECTION.DEMANDSPOONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field12() {
		return Pipedesinfection.PIPEDESINFECTION.RETENTIONTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value1() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPipeIdpipe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPipeWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPipeWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getPipeWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value7() {
		return getVolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getChlorineconcentration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value9() {
		return getDemandactivechlorine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value10() {
		return getDemand70chlorine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value11() {
		return getDemandspoons();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value12() {
		return getRetentiontime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value1(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value2(Integer value) {
		setPipeIdpipe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value3(Integer value) {
		setPipeWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value4(Integer value) {
		setPipeWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value5(Integer value) {
		setPipeWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value6(Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value7(Double value) {
		setVolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value8(Double value) {
		setChlorineconcentration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value9(Double value) {
		setDemandactivechlorine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value10(Double value) {
		setDemand70chlorine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value11(Double value) {
		setDemandspoons(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord value12(Double value) {
		setRetentiontime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PipedesinfectionRecord values(Timestamp value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Double value7, Double value8, Double value9, Double value10, Double value11, Double value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PipedesinfectionRecord
	 */
	public PipedesinfectionRecord() {
		super(Pipedesinfection.PIPEDESINFECTION);
	}

	/**
	 * Create a detached, initialised PipedesinfectionRecord
	 */
	public PipedesinfectionRecord(Timestamp date, Integer pipeIdpipe, Integer pipeWatersystemIdwatersystem, Integer pipeWatersystemCommunityIdcommunity, Integer pipeWatersystemCommunitySubbasinIdsubbasin, Integer count, Double volume, Double chlorineconcentration, Double demandactivechlorine, Double demand70chlorine, Double demandspoons, Double retentiontime) {
		super(Pipedesinfection.PIPEDESINFECTION);

		setValue(0, date);
		setValue(1, pipeIdpipe);
		setValue(2, pipeWatersystemIdwatersystem);
		setValue(3, pipeWatersystemCommunityIdcommunity);
		setValue(4, pipeWatersystemCommunitySubbasinIdsubbasin);
		setValue(5, count);
		setValue(6, volume);
		setValue(7, chlorineconcentration);
		setValue(8, demandactivechlorine);
		setValue(9, demand70chlorine);
		setValue(10, demandspoons);
		setValue(11, retentiontime);
	}
}
