/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record5;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Reliefvalvedesinfection;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReliefvalvedesinfectionRecord extends UpdatableRecordImpl<ReliefvalvedesinfectionRecord> implements Record13<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double, Double> {

	private static final long serialVersionUID = 1851410310;

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DATE</code>.
	 */
	public void setDate(Timestamp value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DATE</code>.
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_IDRELIEFVALVE</code>.
	 */
	public void setReliefvalveIdreliefvalve(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_IDRELIEFVALVE</code>.
	 */
	public Integer getReliefvalveIdreliefvalve() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public void setReliefvalveWatersystemIdwatersystem(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public Integer getReliefvalveWatersystemIdwatersystem() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setReliefvalveWatersystemCommunityIdcommunity(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getReliefvalveWatersystemCommunityIdcommunity() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setReliefvalveWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getReliefvalveWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.COUNT</code>.
	 */
	public void setCount(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.COUNT</code>.
	 */
	public Integer getCount() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.WATERHEIGHT</code>.
	 */
	public void setWaterheight(Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.WATERHEIGHT</code>.
	 */
	public Double getWaterheight() {
		return (Double) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.VOLUME</code>.
	 */
	public void setVolume(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.VOLUME</code>.
	 */
	public Double getVolume() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.CHLORINECONCENTRATION</code>.
	 */
	public void setChlorineconcentration(Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.CHLORINECONCENTRATION</code>.
	 */
	public Double getChlorineconcentration() {
		return (Double) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMANDACTIVECHLORINE</code>.
	 */
	public void setDemandactivechlorine(Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMANDACTIVECHLORINE</code>.
	 */
	public Double getDemandactivechlorine() {
		return (Double) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMAND70CHLORINE</code>.
	 */
	public void setDemand70chlorine(Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMAND70CHLORINE</code>.
	 */
	public Double getDemand70chlorine() {
		return (Double) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMANDSPOONS</code>.
	 */
	public void setDemandspoons(Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMANDSPOONS</code>.
	 */
	public Double getDemandspoons() {
		return (Double) getValue(11);
	}

	/**
	 * Setter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RETENTIONTIME</code>.
	 */
	public void setRetentiontime(Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>PUBLIC.RELIEFVALVEDESINFECTION.RETENTIONTIME</code>.
	 */
	public Double getRetentiontime() {
		return (Double) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record5<Timestamp, Integer, Integer, Integer, Integer> key() {
		return (Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double, Double> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Timestamp, Integer, Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double, Double> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field1() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.RELIEFVALVE_IDRELIEFVALVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field7() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.WATERHEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.VOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field9() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.CHLORINECONCENTRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field10() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.DEMANDACTIVECHLORINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field11() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.DEMAND70CHLORINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field12() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.DEMANDSPOONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field13() {
		return Reliefvalvedesinfection.RELIEFVALVEDESINFECTION.RETENTIONTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value1() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getReliefvalveIdreliefvalve();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getReliefvalveWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getReliefvalveWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getReliefvalveWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value7() {
		return getWaterheight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getVolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value9() {
		return getChlorineconcentration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value10() {
		return getDemandactivechlorine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value11() {
		return getDemand70chlorine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value12() {
		return getDemandspoons();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value13() {
		return getRetentiontime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value1(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value2(Integer value) {
		setReliefvalveIdreliefvalve(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value3(Integer value) {
		setReliefvalveWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value4(Integer value) {
		setReliefvalveWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value5(Integer value) {
		setReliefvalveWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value6(Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value7(Double value) {
		setWaterheight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value8(Double value) {
		setVolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value9(Double value) {
		setChlorineconcentration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value10(Double value) {
		setDemandactivechlorine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value11(Double value) {
		setDemand70chlorine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value12(Double value) {
		setDemandspoons(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord value13(Double value) {
		setRetentiontime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReliefvalvedesinfectionRecord values(Timestamp value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Double value7, Double value8, Double value9, Double value10, Double value11, Double value12, Double value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReliefvalvedesinfectionRecord
	 */
	public ReliefvalvedesinfectionRecord() {
		super(Reliefvalvedesinfection.RELIEFVALVEDESINFECTION);
	}

	/**
	 * Create a detached, initialised ReliefvalvedesinfectionRecord
	 */
	public ReliefvalvedesinfectionRecord(Timestamp date, Integer reliefvalveIdreliefvalve, Integer reliefvalveWatersystemIdwatersystem, Integer reliefvalveWatersystemCommunityIdcommunity, Integer reliefvalveWatersystemCommunitySubbasinIdsubbasin, Integer count, Double waterheight, Double volume, Double chlorineconcentration, Double demandactivechlorine, Double demand70chlorine, Double demandspoons, Double retentiontime) {
		super(Reliefvalvedesinfection.RELIEFVALVEDESINFECTION);

		setValue(0, date);
		setValue(1, reliefvalveIdreliefvalve);
		setValue(2, reliefvalveWatersystemIdwatersystem);
		setValue(3, reliefvalveWatersystemCommunityIdcommunity);
		setValue(4, reliefvalveWatersystemCommunitySubbasinIdsubbasin);
		setValue(5, count);
		setValue(6, waterheight);
		setValue(7, volume);
		setValue(8, chlorineconcentration);
		setValue(9, demandactivechlorine);
		setValue(10, demand70chlorine);
		setValue(11, demandspoons);
		setValue(12, retentiontime);
	}
}
