/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record17;
import org.jooq.Record3;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Watersystem;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatersystemRecord extends UpdatableRecordImpl<WatersystemRecord> implements Record17<Integer, Integer, Integer, String, Integer, Integer, Integer, Byte, Integer, Byte, Short, Byte, Byte, Byte, Short, Short, Byte> {

	private static final long serialVersionUID = -1412148303;

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.IDWATERSYSTEM</code>.
	 */
	public void setIdwatersystem(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.IDWATERSYSTEM</code>.
	 */
	public Integer getIdwatersystem() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setCommunityIdcommunity(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getCommunityIdcommunity() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setCommunitySubbasinIdsubbasin(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.NAME</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.FAMILIESNUM</code>.
	 */
	public void setFamiliesnum(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.FAMILIESNUM</code>.
	 */
	public Integer getFamiliesnum() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.POPULATION</code>. Estimado a 5 miembros por familia
	 */
	public void setPopulation(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.POPULATION</code>. Estimado a 5 miembros por familia
	 */
	public Integer getPopulation() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.POPULATIONFORECAST</code>. Proyección de habitantes en 20 años
	 */
	public void setPopulationforecast(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.POPULATIONFORECAST</code>. Proyección de habitantes en 20 años
	 */
	public Integer getPopulationforecast() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.GROWINGINDEX</code>. Expresado en %
	 */
	public void setGrowingindex(Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.GROWINGINDEX</code>. Expresado en %
	 */
	public Byte getGrowingindex() {
		return (Byte) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.JASSNUM</code>.
	 */
	public void setJassnum(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.JASSNUM</code>.
	 */
	public Integer getJassnum() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.FUTURENEEDEDFLOW</code>.
	 */
	public void setFutureneededflow(Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.FUTURENEEDEDFLOW</code>.
	 */
	public Byte getFutureneededflow() {
		return (Byte) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.RESERVOIRVOLUME</code>. Unidad en metros cúbicos
	 */
	public void setReservoirvolume(Short value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.RESERVOIRVOLUME</code>. Unidad en metros cúbicos
	 */
	public Short getReservoirvolume() {
		return (Short) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.TANKSIDEA</code>. Unidad en metros
	 */
	public void setTanksidea(Byte value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.TANKSIDEA</code>. Unidad en metros
	 */
	public Byte getTanksidea() {
		return (Byte) getValue(11);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.TANKSIDEB</code>. Unidad en metros
	 */
	public void setTanksideb(Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.TANKSIDEB</code>. Unidad en metros
	 */
	public Byte getTanksideb() {
		return (Byte) getValue(12);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.TANKHEIGHT</code>. Unidad en metros
	 */
	public void setTankheight(Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.TANKHEIGHT</code>. Unidad en metros
	 */
	public Byte getTankheight() {
		return (Byte) getValue(13);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.TANKVOLUME</code>. Unidad en metros cúbicos
	 */
	public void setTankvolume(Short value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.TANKVOLUME</code>. Unidad en metros cúbicos
	 */
	public Short getTankvolume() {
		return (Short) getValue(14);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.TANKUSEFULVOLUME</code>. Unidad en metros cúbicos
	 */
	public void setTankusefulvolume(Short value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.TANKUSEFULVOLUME</code>. Unidad en metros cúbicos
	 */
	public Short getTankusefulvolume() {
		return (Short) getValue(15);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.SYSTEMELEVATION</code>. Altura msnm
	 */
	public void setSystemelevation(Byte value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.SYSTEMELEVATION</code>. Altura msnm
	 */
	public Byte getSystemelevation() {
		return (Byte) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<Integer, Integer, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<Integer, Integer, Integer, String, Integer, Integer, Integer, Byte, Integer, Byte, Short, Byte, Byte, Byte, Short, Short, Byte> fieldsRow() {
		return (Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<Integer, Integer, Integer, String, Integer, Integer, Integer, Byte, Integer, Byte, Short, Byte, Byte, Byte, Short, Short, Byte> valuesRow() {
		return (Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Watersystem.WATERSYSTEM.IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Watersystem.WATERSYSTEM.COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Watersystem.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Watersystem.WATERSYSTEM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Watersystem.WATERSYSTEM.FAMILIESNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Watersystem.WATERSYSTEM.POPULATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Watersystem.WATERSYSTEM.POPULATIONFORECAST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field8() {
		return Watersystem.WATERSYSTEM.GROWINGINDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Watersystem.WATERSYSTEM.JASSNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field10() {
		return Watersystem.WATERSYSTEM.FUTURENEEDEDFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field11() {
		return Watersystem.WATERSYSTEM.RESERVOIRVOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field12() {
		return Watersystem.WATERSYSTEM.TANKSIDEA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field13() {
		return Watersystem.WATERSYSTEM.TANKSIDEB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field14() {
		return Watersystem.WATERSYSTEM.TANKHEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field15() {
		return Watersystem.WATERSYSTEM.TANKVOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field16() {
		return Watersystem.WATERSYSTEM.TANKUSEFULVOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field17() {
		return Watersystem.WATERSYSTEM.SYSTEMELEVATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getFamiliesnum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPopulation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getPopulationforecast();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value8() {
		return getGrowingindex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getJassnum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value10() {
		return getFutureneededflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value11() {
		return getReservoirvolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value12() {
		return getTanksidea();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value13() {
		return getTanksideb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value14() {
		return getTankheight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value15() {
		return getTankvolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value16() {
		return getTankusefulvolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value17() {
		return getSystemelevation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value1(Integer value) {
		setIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value2(Integer value) {
		setCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value3(Integer value) {
		setCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value5(Integer value) {
		setFamiliesnum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value6(Integer value) {
		setPopulation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value7(Integer value) {
		setPopulationforecast(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value8(Byte value) {
		setGrowingindex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value9(Integer value) {
		setJassnum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value10(Byte value) {
		setFutureneededflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value11(Short value) {
		setReservoirvolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value12(Byte value) {
		setTanksidea(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value13(Byte value) {
		setTanksideb(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value14(Byte value) {
		setTankheight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value15(Short value) {
		setTankvolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value16(Short value) {
		setTankusefulvolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value17(Byte value) {
		setSystemelevation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, Integer value7, Byte value8, Integer value9, Byte value10, Short value11, Byte value12, Byte value13, Byte value14, Short value15, Short value16, Byte value17) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WatersystemRecord
	 */
	public WatersystemRecord() {
		super(Watersystem.WATERSYSTEM);
	}

	/**
	 * Create a detached, initialised WatersystemRecord
	 */
	public WatersystemRecord(Integer idwatersystem, Integer communityIdcommunity, Integer communitySubbasinIdsubbasin, String name, Integer familiesnum, Integer population, Integer populationforecast, Byte growingindex, Integer jassnum, Byte futureneededflow, Short reservoirvolume, Byte tanksidea, Byte tanksideb, Byte tankheight, Short tankvolume, Short tankusefulvolume, Byte systemelevation) {
		super(Watersystem.WATERSYSTEM);

		setValue(0, idwatersystem);
		setValue(1, communityIdcommunity);
		setValue(2, communitySubbasinIdsubbasin);
		setValue(3, name);
		setValue(4, familiesnum);
		setValue(5, population);
		setValue(6, populationforecast);
		setValue(7, growingindex);
		setValue(8, jassnum);
		setValue(9, futureneededflow);
		setValue(10, reservoirvolume);
		setValue(11, tanksidea);
		setValue(12, tanksideb);
		setValue(13, tankheight);
		setValue(14, tankvolume);
		setValue(15, tankusefulvolume);
		setValue(16, systemelevation);
	}
}
