/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record3;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Watersystem;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatersystemRecord extends UpdatableRecordImpl<WatersystemRecord> implements Record13<Integer, Integer, Integer, String, Integer, Integer, Integer, Double, Double, Integer, Double, Double, Integer> {

	private static final long serialVersionUID = 1446248412;

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.IDWATERSYSTEM</code>.
	 */
	public void setIdwatersystem(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.IDWATERSYSTEM</code>.
	 */
	public Integer getIdwatersystem() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setCommunityIdcommunity(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getCommunityIdcommunity() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setCommunitySubbasinIdsubbasin(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.NAME</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.FAMILIESNUM</code>.
	 */
	public void setFamiliesnum(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.FAMILIESNUM</code>.
	 */
	public Integer getFamiliesnum() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.POPULATION</code>. Estimado a 5 miembros por familia
	 */
	public void setPopulation(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.POPULATION</code>. Estimado a 5 miembros por familia
	 */
	public Integer getPopulation() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.POPULATIONFORECAST</code>. Proyección de habitantes en 20 años
	 */
	public void setPopulationforecast(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.POPULATIONFORECAST</code>. Proyección de habitantes en 20 años
	 */
	public Integer getPopulationforecast() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.GROWINGINDEX</code>. Expresado en %
	 */
	public void setGrowingindex(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.GROWINGINDEX</code>. Expresado en %
	 */
	public Double getGrowingindex() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.ENDOWMENT</code>.
	 */
	public void setEndowment(Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.ENDOWMENT</code>.
	 */
	public Double getEndowment() {
		return (Double) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.JASSNUM</code>.
	 */
	public void setJassnum(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.JASSNUM</code>.
	 */
	public Integer getJassnum() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.FUTURENEEDEDFLOW</code>.
	 */
	public void setFutureneededflow(Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.FUTURENEEDEDFLOW</code>.
	 */
	public Double getFutureneededflow() {
		return (Double) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.RESERVOIRVOLUME</code>. Unidad en metros cúbicos
	 */
	public void setReservoirvolume(Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.RESERVOIRVOLUME</code>. Unidad en metros cúbicos
	 */
	public Double getReservoirvolume() {
		return (Double) getValue(11);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM.SYSTEMELEVATION</code>. Altura msnm
	 */
	public void setSystemelevation(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM.SYSTEMELEVATION</code>. Altura msnm
	 */
	public Integer getSystemelevation() {
		return (Integer) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<Integer, Integer, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, Integer, Integer, String, Integer, Integer, Integer, Double, Double, Integer, Double, Double, Integer> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, Integer, Integer, String, Integer, Integer, Integer, Double, Double, Integer, Double, Double, Integer> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Watersystem.WATERSYSTEM.IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Watersystem.WATERSYSTEM.COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Watersystem.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Watersystem.WATERSYSTEM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Watersystem.WATERSYSTEM.FAMILIESNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Watersystem.WATERSYSTEM.POPULATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Watersystem.WATERSYSTEM.POPULATIONFORECAST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Watersystem.WATERSYSTEM.GROWINGINDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field9() {
		return Watersystem.WATERSYSTEM.ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Watersystem.WATERSYSTEM.JASSNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field11() {
		return Watersystem.WATERSYSTEM.FUTURENEEDEDFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field12() {
		return Watersystem.WATERSYSTEM.RESERVOIRVOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Watersystem.WATERSYSTEM.SYSTEMELEVATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getFamiliesnum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPopulation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getPopulationforecast();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getGrowingindex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value9() {
		return getEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getJassnum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value11() {
		return getFutureneededflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value12() {
		return getReservoirvolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getSystemelevation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value1(Integer value) {
		setIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value2(Integer value) {
		setCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value3(Integer value) {
		setCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value5(Integer value) {
		setFamiliesnum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value6(Integer value) {
		setPopulation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value7(Integer value) {
		setPopulationforecast(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value8(Double value) {
		setGrowingindex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value9(Double value) {
		setEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value10(Integer value) {
		setJassnum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value11(Double value) {
		setFutureneededflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value12(Double value) {
		setReservoirvolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord value13(Integer value) {
		setSystemelevation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, Integer value7, Double value8, Double value9, Integer value10, Double value11, Double value12, Integer value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WatersystemRecord
	 */
	public WatersystemRecord() {
		super(Watersystem.WATERSYSTEM);
	}

	/**
	 * Create a detached, initialised WatersystemRecord
	 */
	public WatersystemRecord(Integer idwatersystem, Integer communityIdcommunity, Integer communitySubbasinIdsubbasin, String name, Integer familiesnum, Integer population, Integer populationforecast, Double growingindex, Double endowment, Integer jassnum, Double futureneededflow, Double reservoirvolume, Integer systemelevation) {
		super(Watersystem.WATERSYSTEM);

		setValue(0, idwatersystem);
		setValue(1, communityIdcommunity);
		setValue(2, communitySubbasinIdsubbasin);
		setValue(3, name);
		setValue(4, familiesnum);
		setValue(5, population);
		setValue(6, populationforecast);
		setValue(7, growingindex);
		setValue(8, endowment);
		setValue(9, jassnum);
		setValue(10, futureneededflow);
		setValue(11, reservoirvolume);
		setValue(12, systemelevation);
	}
}