/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.WatersystemHasWaterspring;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatersystemHasWaterspringRecord extends UpdatableRecordImpl<WatersystemHasWaterspringRecord> implements Record4<Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -998064367;

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public void setWatersystemIdwatersystem(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public Integer getWatersystemIdwatersystem() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public void setWatersystemCommunityIdcommunity(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public Integer getWatersystemCommunityIdcommunity() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public void setWatersystemCommunitySubbasinIdsubbasin(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public Integer getWatersystemCommunitySubbasinIdsubbasin() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSPRING_IDWATERSPRING</code>.
	 */
	public void setWaterspringIdwaterspring(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSPRING_IDWATERSPRING</code>.
	 */
	public Integer getWaterspringIdwaterspring() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record4<Integer, Integer, Integer, Integer> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_IDWATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_IDCOMMUNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSPRING_IDWATERSPRING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getWatersystemIdwatersystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getWatersystemCommunityIdcommunity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getWatersystemCommunitySubbasinIdsubbasin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getWaterspringIdwaterspring();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemHasWaterspringRecord value1(Integer value) {
		setWatersystemIdwatersystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemHasWaterspringRecord value2(Integer value) {
		setWatersystemCommunityIdcommunity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemHasWaterspringRecord value3(Integer value) {
		setWatersystemCommunitySubbasinIdsubbasin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemHasWaterspringRecord value4(Integer value) {
		setWaterspringIdwaterspring(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemHasWaterspringRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WatersystemHasWaterspringRecord
	 */
	public WatersystemHasWaterspringRecord() {
		super(WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING);
	}

	/**
	 * Create a detached, initialised WatersystemHasWaterspringRecord
	 */
	public WatersystemHasWaterspringRecord(Integer watersystemIdwatersystem, Integer watersystemCommunityIdcommunity, Integer watersystemCommunitySubbasinIdsubbasin, Integer waterspringIdwaterspring) {
		super(WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING);

		setValue(0, watersystemIdwatersystem);
		setValue(1, watersystemCommunityIdcommunity);
		setValue(2, watersystemCommunitySubbasinIdsubbasin);
		setValue(3, waterspringIdwaterspring);
	}
}
