/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.BackupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Backup extends TableImpl<BackupRecord> {

	private static final long serialVersionUID = -205102729;

	/**
	 * The reference instance of <code>PUBLIC.BACKUP</code>
	 */
	public static final Backup BACKUP = new Backup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BackupRecord> getRecordType() {
		return BackupRecord.class;
	}

	/**
	 * The column <code>PUBLIC.BACKUP.IDBACKUP</code>.
	 */
	public final TableField<BackupRecord, Integer> IDBACKUP = createField("IDBACKUP", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.BACKUP.FILEPATH</code>.
	 */
	public final TableField<BackupRecord, String> FILEPATH = createField("FILEPATH", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.BACKUP.FILENAME</code>.
	 */
	public final TableField<BackupRecord, String> FILENAME = createField("FILENAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.BACKUP.SERVICENAME</code>.
	 */
	public final TableField<BackupRecord, String> SERVICENAME = createField("SERVICENAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.BACKUP.LASTATTEMPT</code>.
	 */
	public final TableField<BackupRecord, Timestamp> LASTATTEMPT = createField("LASTATTEMPT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>PUBLIC.BACKUP</code> table reference
	 */
	public Backup() {
		this("BACKUP", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.BACKUP</code> table reference
	 */
	public Backup(String alias) {
		this(alias, BACKUP);
	}

	private Backup(String alias, Table<BackupRecord> aliased) {
		this(alias, aliased, null);
	}

	private Backup(String alias, Table<BackupRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<BackupRecord, Integer> getIdentity() {
		return Keys.IDENTITY_BACKUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BackupRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_745;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BackupRecord>> getKeys() {
		return Arrays.<UniqueKey<BackupRecord>>asList(Keys.CONSTRAINT_745);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Backup as(String alias) {
		return new Backup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Backup rename(String name) {
		return new Backup(name, null);
	}
}
