/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.CatchmentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Catchment extends TableImpl<CatchmentRecord> {

	private static final long serialVersionUID = -2028718693;

	/**
	 * The reference instance of <code>PUBLIC.CATCHMENT</code>
	 */
	public static final Catchment CATCHMENT = new Catchment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CatchmentRecord> getRecordType() {
		return CatchmentRecord.class;
	}

	/**
	 * The column <code>PUBLIC.CATCHMENT.IDCATCHMENT</code>.
	 */
	public final TableField<CatchmentRecord, Integer> IDCATCHMENT = createField("IDCATCHMENT", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public final TableField<CatchmentRecord, Integer> WATERSYSTEM_IDWATERSYSTEM = createField("WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<CatchmentRecord, Integer> WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<CatchmentRecord, Integer> WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.NAME</code>.
	 */
	public final TableField<CatchmentRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.WIDTH</code>.
	 */
	public final TableField<CatchmentRecord, Double> WIDTH = createField("WIDTH", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.LENGTH</code>.
	 */
	public final TableField<CatchmentRecord, Double> LENGTH = createField("LENGTH", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.HEIGHT</code>.
	 */
	public final TableField<CatchmentRecord, Double> HEIGHT = createField("HEIGHT", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CATCHMENT.COUNT</code>.
	 */
	public final TableField<CatchmentRecord, Integer> COUNT = createField("COUNT", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>PUBLIC.CATCHMENT</code> table reference
	 */
	public Catchment() {
		this("CATCHMENT", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.CATCHMENT</code> table reference
	 */
	public Catchment(String alias) {
		this(alias, CATCHMENT);
	}

	private Catchment(String alias, Table<CatchmentRecord> aliased) {
		this(alias, aliased, null);
	}

	private Catchment(String alias, Table<CatchmentRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CatchmentRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CATCHMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CatchmentRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CatchmentRecord>> getKeys() {
		return Arrays.<UniqueKey<CatchmentRecord>>asList(Keys.CONSTRAINT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<CatchmentRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<CatchmentRecord, ?>>asList(Keys.FK_CATCHMENT_WATERSYSTEM1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Catchment as(String alias) {
		return new Catchment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Catchment rename(String name) {
		return new Catchment(name, null);
	}
}
