/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.ChlorinecalculationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chlorinecalculation extends TableImpl<ChlorinecalculationRecord> {

	private static final long serialVersionUID = -1938786347;

	/**
	 * The reference instance of <code>PUBLIC.CHLORINECALCULATION</code>
	 */
	public static final Chlorinecalculation CHLORINECALCULATION = new Chlorinecalculation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ChlorinecalculationRecord> getRecordType() {
		return ChlorinecalculationRecord.class;
	}

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.DATE</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Timestamp> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_IDWATERSYSTEM</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Integer> WATERSYSTEM_IDWATERSYSTEM = createField("WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Integer> WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Integer> WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.FAMILIESNUM</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Integer> FAMILIESNUM = createField("FAMILIESNUM", org.jooq.impl.SQLDataType.INTEGER, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.POPULATION</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Integer> POPULATION = createField("POPULATION", org.jooq.impl.SQLDataType.INTEGER, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.TANKVOLUME</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> TANKVOLUME = createField("TANKVOLUME", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.ENDOWMENT</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> ENDOWMENT = createField("ENDOWMENT", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINEPURENESS</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINEPURENESS = createField("CHLORINEPURENESS", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.NATURALFLOW</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> NATURALFLOW = createField("NATURALFLOW", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINATEDFLOW</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINATEDFLOW = createField("CHLORINATEDFLOW", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINETYPE</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, String> CHLORINETYPE = createField("CHLORINETYPE", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.DRIPPINGHOURSPERDAY</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> DRIPPINGHOURSPERDAY = createField("DRIPPINGHOURSPERDAY", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINEDEMAND</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINEDEMAND = createField("CHLORINEDEMAND", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINEPRICE</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINEPRICE = createField("CHLORINEPRICE", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.RELOADTIME</code>. INPUT
	 */
	public final TableField<ChlorinecalculationRecord, Double> RELOADTIME = createField("RELOADTIME", org.jooq.impl.SQLDataType.DOUBLE, this, "INPUT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINEDOSEPERFORTNIGHT</code>. RESULT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINEDOSEPERFORTNIGHT = createField("CHLORINEDOSEPERFORTNIGHT", org.jooq.impl.SQLDataType.DOUBLE, this, "RESULT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINEDOSEPERMONTH</code>. RESULT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINEDOSEPERMONTH = createField("CHLORINEDOSEPERMONTH", org.jooq.impl.SQLDataType.DOUBLE, this, "RESULT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.DRIPPINGFLOWINML</code>. RESULT
	 */
	public final TableField<ChlorinecalculationRecord, Double> DRIPPINGFLOWINML = createField("DRIPPINGFLOWINML", org.jooq.impl.SQLDataType.DOUBLE, this, "RESULT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.DRIPPINGFLOWINDROPS</code>. RESULT
	 */
	public final TableField<ChlorinecalculationRecord, Double> DRIPPINGFLOWINDROPS = createField("DRIPPINGFLOWINDROPS", org.jooq.impl.SQLDataType.DOUBLE, this, "RESULT");

	/**
	 * The column <code>PUBLIC.CHLORINECALCULATION.CHLORINATIONCOST</code>. RESULT
	 */
	public final TableField<ChlorinecalculationRecord, Double> CHLORINATIONCOST = createField("CHLORINATIONCOST", org.jooq.impl.SQLDataType.DOUBLE, this, "RESULT");

	/**
	 * Create a <code>PUBLIC.CHLORINECALCULATION</code> table reference
	 */
	public Chlorinecalculation() {
		this("CHLORINECALCULATION", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.CHLORINECALCULATION</code> table reference
	 */
	public Chlorinecalculation(String alias) {
		this(alias, CHLORINECALCULATION);
	}

	private Chlorinecalculation(String alias, Table<ChlorinecalculationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Chlorinecalculation(String alias, Table<ChlorinecalculationRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ChlorinecalculationRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_E;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ChlorinecalculationRecord>> getKeys() {
		return Arrays.<UniqueKey<ChlorinecalculationRecord>>asList(Keys.CONSTRAINT_E);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ChlorinecalculationRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ChlorinecalculationRecord, ?>>asList(Keys.FK_CHLORINECALCULATION_WATERSYSTEM1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Chlorinecalculation as(String alias) {
		return new Chlorinecalculation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Chlorinecalculation rename(String name) {
		return new Chlorinecalculation(name, null);
	}
}
