/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.DesinfectionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Desinfection extends TableImpl<DesinfectionRecord> {

	private static final long serialVersionUID = 1210212105;

	/**
	 * The reference instance of <code>PUBLIC.DESINFECTION</code>
	 */
	public static final Desinfection DESINFECTION = new Desinfection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DesinfectionRecord> getRecordType() {
		return DesinfectionRecord.class;
	}

	/**
	 * The column <code>PUBLIC.DESINFECTION.DATE</code>.
	 */
	public final TableField<DesinfectionRecord, Timestamp> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DESINFECTION.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public final TableField<DesinfectionRecord, Integer> WATERSYSTEM_IDWATERSYSTEM = createField("WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DESINFECTION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<DesinfectionRecord, Integer> WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DESINFECTION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<DesinfectionRecord, Integer> WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DESINFECTION.CHLORINETYPE</code>.
	 */
	public final TableField<DesinfectionRecord, String> CHLORINETYPE = createField("CHLORINETYPE", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DESINFECTION.CHLORINEPURENESS</code>.
	 */
	public final TableField<DesinfectionRecord, Double> CHLORINEPURENESS = createField("CHLORINEPURENESS", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.DESINFECTION.CHLORINEPRICE</code>.
	 */
	public final TableField<DesinfectionRecord, Double> CHLORINEPRICE = createField("CHLORINEPRICE", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.DESINFECTION</code> table reference
	 */
	public Desinfection() {
		this("DESINFECTION", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.DESINFECTION</code> table reference
	 */
	public Desinfection(String alias) {
		this(alias, DESINFECTION);
	}

	private Desinfection(String alias, Table<DesinfectionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Desinfection(String alias, Table<DesinfectionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DesinfectionRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_3F;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DesinfectionRecord>> getKeys() {
		return Arrays.<UniqueKey<DesinfectionRecord>>asList(Keys.CONSTRAINT_3F);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<DesinfectionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<DesinfectionRecord, ?>>asList(Keys.FK_DESINFECTION_WATERSYSTEM1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Desinfection as(String alias) {
		return new Desinfection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Desinfection rename(String name) {
		return new Desinfection(name, null);
	}
}
