/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.PipedesinfectionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pipedesinfection extends TableImpl<PipedesinfectionRecord> {

	private static final long serialVersionUID = -1945730630;

	/**
	 * The reference instance of <code>PUBLIC.PIPEDESINFECTION</code>
	 */
	public static final Pipedesinfection PIPEDESINFECTION = new Pipedesinfection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PipedesinfectionRecord> getRecordType() {
		return PipedesinfectionRecord.class;
	}

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.DATE</code>.
	 */
	public final TableField<PipedesinfectionRecord, Timestamp> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.PIPE_IDPIPE</code>.
	 */
	public final TableField<PipedesinfectionRecord, Integer> PIPE_IDPIPE = createField("PIPE_IDPIPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public final TableField<PipedesinfectionRecord, Integer> PIPE_WATERSYSTEM_IDWATERSYSTEM = createField("PIPE_WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<PipedesinfectionRecord, Integer> PIPE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("PIPE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.PIPE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<PipedesinfectionRecord, Integer> PIPE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("PIPE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.COUNT</code>.
	 */
	public final TableField<PipedesinfectionRecord, Integer> COUNT = createField("COUNT", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.VOLUME</code>.
	 */
	public final TableField<PipedesinfectionRecord, Double> VOLUME = createField("VOLUME", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.CHLORINECONCENTRATION</code>.
	 */
	public final TableField<PipedesinfectionRecord, Double> CHLORINECONCENTRATION = createField("CHLORINECONCENTRATION", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.DEMANDACTIVECHLORINE</code>.
	 */
	public final TableField<PipedesinfectionRecord, Double> DEMANDACTIVECHLORINE = createField("DEMANDACTIVECHLORINE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.DEMAND70CHLORINE</code>.
	 */
	public final TableField<PipedesinfectionRecord, Double> DEMAND70CHLORINE = createField("DEMAND70CHLORINE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.DEMANDSPOONS</code>.
	 */
	public final TableField<PipedesinfectionRecord, Double> DEMANDSPOONS = createField("DEMANDSPOONS", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.PIPEDESINFECTION.RETENTIONTIME</code>.
	 */
	public final TableField<PipedesinfectionRecord, Double> RETENTIONTIME = createField("RETENTIONTIME", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * Create a <code>PUBLIC.PIPEDESINFECTION</code> table reference
	 */
	public Pipedesinfection() {
		this("PIPEDESINFECTION", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.PIPEDESINFECTION</code> table reference
	 */
	public Pipedesinfection(String alias) {
		this(alias, PIPEDESINFECTION);
	}

	private Pipedesinfection(String alias, Table<PipedesinfectionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Pipedesinfection(String alias, Table<PipedesinfectionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PipedesinfectionRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_3B;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PipedesinfectionRecord>> getKeys() {
		return Arrays.<UniqueKey<PipedesinfectionRecord>>asList(Keys.CONSTRAINT_3B);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PipedesinfectionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PipedesinfectionRecord, ?>>asList(Keys.FK_PIPEDESINFECTION_PIPE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Pipedesinfection as(String alias) {
		return new Pipedesinfection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Pipedesinfection rename(String name) {
		return new Pipedesinfection(name, null);
	}
}
