/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.ReliefvalveRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reliefvalve extends TableImpl<ReliefvalveRecord> {

	private static final long serialVersionUID = -68893995;

	/**
	 * The reference instance of <code>PUBLIC.RELIEFVALVE</code>
	 */
	public static final Reliefvalve RELIEFVALVE = new Reliefvalve();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReliefvalveRecord> getRecordType() {
		return ReliefvalveRecord.class;
	}

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.IDRELIEFVALVE</code>.
	 */
	public final TableField<ReliefvalveRecord, Integer> IDRELIEFVALVE = createField("IDRELIEFVALVE", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public final TableField<ReliefvalveRecord, Integer> WATERSYSTEM_IDWATERSYSTEM = createField("WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<ReliefvalveRecord, Integer> WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<ReliefvalveRecord, Integer> WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.NAME</code>.
	 */
	public final TableField<ReliefvalveRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.WIDTH</code>.
	 */
	public final TableField<ReliefvalveRecord, Double> WIDTH = createField("WIDTH", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.LENGTH</code>.
	 */
	public final TableField<ReliefvalveRecord, Double> LENGTH = createField("LENGTH", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.HEIGHT</code>.
	 */
	public final TableField<ReliefvalveRecord, Double> HEIGHT = createField("HEIGHT", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVE.COUNT</code>.
	 */
	public final TableField<ReliefvalveRecord, Integer> COUNT = createField("COUNT", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>PUBLIC.RELIEFVALVE</code> table reference
	 */
	public Reliefvalve() {
		this("RELIEFVALVE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.RELIEFVALVE</code> table reference
	 */
	public Reliefvalve(String alias) {
		this(alias, RELIEFVALVE);
	}

	private Reliefvalve(String alias, Table<ReliefvalveRecord> aliased) {
		this(alias, aliased, null);
	}

	private Reliefvalve(String alias, Table<ReliefvalveRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ReliefvalveRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RELIEFVALVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReliefvalveRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_EA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReliefvalveRecord>> getKeys() {
		return Arrays.<UniqueKey<ReliefvalveRecord>>asList(Keys.CONSTRAINT_EA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ReliefvalveRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ReliefvalveRecord, ?>>asList(Keys.FK_RELIEFVALVE_WATERSYSTEM1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Reliefvalve as(String alias) {
		return new Reliefvalve(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Reliefvalve rename(String name) {
		return new Reliefvalve(name, null);
	}
}
