/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.ReliefvalvedesinfectionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reliefvalvedesinfection extends TableImpl<ReliefvalvedesinfectionRecord> {

	private static final long serialVersionUID = -62574490;

	/**
	 * The reference instance of <code>PUBLIC.RELIEFVALVEDESINFECTION</code>
	 */
	public static final Reliefvalvedesinfection RELIEFVALVEDESINFECTION = new Reliefvalvedesinfection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReliefvalvedesinfectionRecord> getRecordType() {
		return ReliefvalvedesinfectionRecord.class;
	}

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.DATE</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Timestamp> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_IDRELIEFVALVE</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Integer> RELIEFVALVE_IDRELIEFVALVE = createField("RELIEFVALVE_IDRELIEFVALVE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Integer> RELIEFVALVE_WATERSYSTEM_IDWATERSYSTEM = createField("RELIEFVALVE_WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Integer> RELIEFVALVE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("RELIEFVALVE_WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.RELIEFVALVE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Integer> RELIEFVALVE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("RELIEFVALVE_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.COUNT</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Integer> COUNT = createField("COUNT", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.WATERHEIGHT</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> WATERHEIGHT = createField("WATERHEIGHT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.VOLUME</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> VOLUME = createField("VOLUME", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.CHLORINECONCENTRATION</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> CHLORINECONCENTRATION = createField("CHLORINECONCENTRATION", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMANDACTIVECHLORINE</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> DEMANDACTIVECHLORINE = createField("DEMANDACTIVECHLORINE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMAND70CHLORINE</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> DEMAND70CHLORINE = createField("DEMAND70CHLORINE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.DEMANDSPOONS</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> DEMANDSPOONS = createField("DEMANDSPOONS", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.RELIEFVALVEDESINFECTION.RETENTIONTIME</code>.
	 */
	public final TableField<ReliefvalvedesinfectionRecord, Double> RETENTIONTIME = createField("RETENTIONTIME", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * Create a <code>PUBLIC.RELIEFVALVEDESINFECTION</code> table reference
	 */
	public Reliefvalvedesinfection() {
		this("RELIEFVALVEDESINFECTION", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.RELIEFVALVEDESINFECTION</code> table reference
	 */
	public Reliefvalvedesinfection(String alias) {
		this(alias, RELIEFVALVEDESINFECTION);
	}

	private Reliefvalvedesinfection(String alias, Table<ReliefvalvedesinfectionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Reliefvalvedesinfection(String alias, Table<ReliefvalvedesinfectionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReliefvalvedesinfectionRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_74;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReliefvalvedesinfectionRecord>> getKeys() {
		return Arrays.<UniqueKey<ReliefvalvedesinfectionRecord>>asList(Keys.CONSTRAINT_74);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ReliefvalvedesinfectionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ReliefvalvedesinfectionRecord, ?>>asList(Keys.FK_RELIEFVALVEDESINFECTION_RELIEFVALVE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Reliefvalvedesinfection as(String alias) {
		return new Reliefvalvedesinfection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Reliefvalvedesinfection rename(String name) {
		return new Reliefvalvedesinfection(name, null);
	}
}
