/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.WatersystemHasWaterspringRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatersystemHasWaterspring extends TableImpl<WatersystemHasWaterspringRecord> {

	private static final long serialVersionUID = -1951660480;

	/**
	 * The reference instance of <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING</code>
	 */
	public static final WatersystemHasWaterspring WATERSYSTEM_HAS_WATERSPRING = new WatersystemHasWaterspring();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WatersystemHasWaterspringRecord> getRecordType() {
		return WatersystemHasWaterspringRecord.class;
	}

	/**
	 * The column <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_IDWATERSYSTEM</code>.
	 */
	public final TableField<WatersystemHasWaterspringRecord, Integer> WATERSYSTEM_IDWATERSYSTEM = createField("WATERSYSTEM_IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<WatersystemHasWaterspringRecord, Integer> WATERSYSTEM_COMMUNITY_IDCOMMUNITY = createField("WATERSYSTEM_COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<WatersystemHasWaterspringRecord, Integer> WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN = createField("WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING.WATERSPRING_IDWATERSPRING</code>.
	 */
	public final TableField<WatersystemHasWaterspringRecord, Integer> WATERSPRING_IDWATERSPRING = createField("WATERSPRING_IDWATERSPRING", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING</code> table reference
	 */
	public WatersystemHasWaterspring() {
		this("WATERSYSTEM_HAS_WATERSPRING", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.WATERSYSTEM_HAS_WATERSPRING</code> table reference
	 */
	public WatersystemHasWaterspring(String alias) {
		this(alias, WATERSYSTEM_HAS_WATERSPRING);
	}

	private WatersystemHasWaterspring(String alias, Table<WatersystemHasWaterspringRecord> aliased) {
		this(alias, aliased, null);
	}

	private WatersystemHasWaterspring(String alias, Table<WatersystemHasWaterspringRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WatersystemHasWaterspringRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WatersystemHasWaterspringRecord>> getKeys() {
		return Arrays.<UniqueKey<WatersystemHasWaterspringRecord>>asList(Keys.CONSTRAINT_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<WatersystemHasWaterspringRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<WatersystemHasWaterspringRecord, ?>>asList(Keys.FK_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM1, Keys.FK_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WatersystemHasWaterspring as(String alias) {
		return new WatersystemHasWaterspring(alias, this);
	}

	/**
	 * Rename this table
	 */
	public WatersystemHasWaterspring rename(String name) {
		return new WatersystemHasWaterspring(name, null);
	}
}
