/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.Keys;
import org.ongawa.peru.chlorination.persistence.db.jooq.Public;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.WatersystemRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Watersystem extends TableImpl<WatersystemRecord> {

	private static final long serialVersionUID = 1498398998;

	/**
	 * The reference instance of <code>PUBLIC.WATERSYSTEM</code>
	 */
	public static final Watersystem WATERSYSTEM = new Watersystem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WatersystemRecord> getRecordType() {
		return WatersystemRecord.class;
	}

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.IDWATERSYSTEM</code>.
	 */
	public final TableField<WatersystemRecord, Integer> IDWATERSYSTEM = createField("IDWATERSYSTEM", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.COMMUNITY_IDCOMMUNITY</code>.
	 */
	public final TableField<WatersystemRecord, Integer> COMMUNITY_IDCOMMUNITY = createField("COMMUNITY_IDCOMMUNITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN</code>.
	 */
	public final TableField<WatersystemRecord, Integer> COMMUNITY_SUBBASIN_IDSUBBASIN = createField("COMMUNITY_SUBBASIN_IDSUBBASIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.NAME</code>.
	 */
	public final TableField<WatersystemRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.FAMILIESNUM</code>.
	 */
	public final TableField<WatersystemRecord, Integer> FAMILIESNUM = createField("FAMILIESNUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.POPULATION</code>. Estimado a 5 miembros por familia
	 */
	public final TableField<WatersystemRecord, Integer> POPULATION = createField("POPULATION", org.jooq.impl.SQLDataType.INTEGER, this, "Estimado a 5 miembros por familia");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.POPULATIONFORECAST</code>. Proyección de habitantes en 20 años
	 */
	public final TableField<WatersystemRecord, Integer> POPULATIONFORECAST = createField("POPULATIONFORECAST", org.jooq.impl.SQLDataType.INTEGER, this, "Proyección de habitantes en 20 años");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.GROWINGINDEX</code>. Expresado en %
	 */
	public final TableField<WatersystemRecord, Double> GROWINGINDEX = createField("GROWINGINDEX", org.jooq.impl.SQLDataType.DOUBLE, this, "Expresado en %");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.ENDOWMENT</code>.
	 */
	public final TableField<WatersystemRecord, Double> ENDOWMENT = createField("ENDOWMENT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.JASSNUM</code>.
	 */
	public final TableField<WatersystemRecord, Integer> JASSNUM = createField("JASSNUM", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.FUTURENEEDEDFLOW</code>.
	 */
	public final TableField<WatersystemRecord, Double> FUTURENEEDEDFLOW = createField("FUTURENEEDEDFLOW", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.RESERVOIRVOLUME</code>. Unidad en metros cúbicos
	 */
	public final TableField<WatersystemRecord, Double> RESERVOIRVOLUME = createField("RESERVOIRVOLUME", org.jooq.impl.SQLDataType.DOUBLE, this, "Unidad en metros cúbicos");

	/**
	 * The column <code>PUBLIC.WATERSYSTEM.SYSTEMELEVATION</code>. Altura msnm
	 */
	public final TableField<WatersystemRecord, Integer> SYSTEMELEVATION = createField("SYSTEMELEVATION", org.jooq.impl.SQLDataType.INTEGER, this, "Altura msnm");

	/**
	 * Create a <code>PUBLIC.WATERSYSTEM</code> table reference
	 */
	public Watersystem() {
		this("WATERSYSTEM", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.WATERSYSTEM</code> table reference
	 */
	public Watersystem(String alias) {
		this(alias, WATERSYSTEM);
	}

	private Watersystem(String alias, Table<WatersystemRecord> aliased) {
		this(alias, aliased, null);
	}

	private Watersystem(String alias, Table<WatersystemRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<WatersystemRecord, Integer> getIdentity() {
		return Keys.IDENTITY_WATERSYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WatersystemRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_C;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WatersystemRecord>> getKeys() {
		return Arrays.<UniqueKey<WatersystemRecord>>asList(Keys.CONSTRAINT_C);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<WatersystemRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<WatersystemRecord, ?>>asList(Keys.FK_WATERSYSTEM_COMMUNITY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Watersystem as(String alias) {
		return new Watersystem(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Watersystem rename(String name) {
		return new Watersystem(name, null);
	}
}