/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Chlorinecalculation;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Community;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuredflow;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuringpoint;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Subbasin;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Waterspring;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Watersystem;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.WatersystemHasWaterspring;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.ChlorinecalculationRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.CommunityRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.MeasuredflowRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.MeasuringpointRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.SubbasinRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.WaterspringRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.WatersystemHasWaterspringRecord;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.records.WatersystemRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<SubbasinRecord, Integer> IDENTITY_SUBBASIN = Identities0.IDENTITY_SUBBASIN;
	public static final Identity<CommunityRecord, Integer> IDENTITY_COMMUNITY = Identities0.IDENTITY_COMMUNITY;
	public static final Identity<WatersystemRecord, Integer> IDENTITY_WATERSYSTEM = Identities0.IDENTITY_WATERSYSTEM;
	public static final Identity<WaterspringRecord, Integer> IDENTITY_WATERSPRING = Identities0.IDENTITY_WATERSPRING;
	public static final Identity<MeasuringpointRecord, Integer> IDENTITY_MEASURINGPOINT = Identities0.IDENTITY_MEASURINGPOINT;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<SubbasinRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
	public static final UniqueKey<CommunityRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
	public static final UniqueKey<WatersystemRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
	public static final UniqueKey<WaterspringRecord> CONSTRAINT_CA = UniqueKeys0.CONSTRAINT_CA;
	public static final UniqueKey<WatersystemHasWaterspringRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
	public static final UniqueKey<MeasuringpointRecord> CONSTRAINT_48 = UniqueKeys0.CONSTRAINT_48;
	public static final UniqueKey<MeasuredflowRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
	public static final UniqueKey<ChlorinecalculationRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<CommunityRecord, SubbasinRecord> FK_COMMUNITY_SUBBASIN1 = ForeignKeys0.FK_COMMUNITY_SUBBASIN1;
	public static final ForeignKey<WatersystemRecord, CommunityRecord> FK_WATERSYSTEM_COMMUNITY1 = ForeignKeys0.FK_WATERSYSTEM_COMMUNITY1;
	public static final ForeignKey<WatersystemHasWaterspringRecord, WatersystemRecord> FK_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM1 = ForeignKeys0.FK_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM1;
	public static final ForeignKey<WatersystemHasWaterspringRecord, WaterspringRecord> FK_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING1 = ForeignKeys0.FK_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING1;
	public static final ForeignKey<MeasuringpointRecord, WatersystemHasWaterspringRecord> FK_MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING1 = ForeignKeys0.FK_MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING1;
	public static final ForeignKey<MeasuredflowRecord, MeasuringpointRecord> FK_MEASUREDFLOW_MEASURINGPOINT1 = ForeignKeys0.FK_MEASUREDFLOW_MEASURINGPOINT1;
	public static final ForeignKey<ChlorinecalculationRecord, WatersystemRecord> FK_CHLORINECALCULATION_WATERSYSTEM1 = ForeignKeys0.FK_CHLORINECALCULATION_WATERSYSTEM1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<SubbasinRecord, Integer> IDENTITY_SUBBASIN = createIdentity(Subbasin.SUBBASIN, Subbasin.SUBBASIN.IDSUBBASIN);
		public static Identity<CommunityRecord, Integer> IDENTITY_COMMUNITY = createIdentity(Community.COMMUNITY, Community.COMMUNITY.IDCOMMUNITY);
		public static Identity<WatersystemRecord, Integer> IDENTITY_WATERSYSTEM = createIdentity(Watersystem.WATERSYSTEM, Watersystem.WATERSYSTEM.IDWATERSYSTEM);
		public static Identity<WaterspringRecord, Integer> IDENTITY_WATERSPRING = createIdentity(Waterspring.WATERSPRING, Waterspring.WATERSPRING.IDWATERSPRING);
		public static Identity<MeasuringpointRecord, Integer> IDENTITY_MEASURINGPOINT = createIdentity(Measuringpoint.MEASURINGPOINT, Measuringpoint.MEASURINGPOINT.IDMEASURINGPOINT);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<SubbasinRecord> CONSTRAINT_B = createUniqueKey(Subbasin.SUBBASIN, Subbasin.SUBBASIN.IDSUBBASIN);
		public static final UniqueKey<CommunityRecord> CONSTRAINT_4 = createUniqueKey(Community.COMMUNITY, Community.COMMUNITY.IDCOMMUNITY, Community.COMMUNITY.SUBBASIN_IDSUBBASIN);
		public static final UniqueKey<WatersystemRecord> CONSTRAINT_C = createUniqueKey(Watersystem.WATERSYSTEM, Watersystem.WATERSYSTEM.IDWATERSYSTEM, Watersystem.WATERSYSTEM.COMMUNITY_IDCOMMUNITY, Watersystem.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN);
		public static final UniqueKey<WaterspringRecord> CONSTRAINT_CA = createUniqueKey(Waterspring.WATERSPRING, Waterspring.WATERSPRING.IDWATERSPRING);
		public static final UniqueKey<WatersystemHasWaterspringRecord> CONSTRAINT_2 = createUniqueKey(WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_IDWATERSYSTEM, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_IDCOMMUNITY, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSPRING_IDWATERSPRING);
		public static final UniqueKey<MeasuringpointRecord> CONSTRAINT_48 = createUniqueKey(Measuringpoint.MEASURINGPOINT, Measuringpoint.MEASURINGPOINT.IDMEASURINGPOINT, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING);
		public static final UniqueKey<MeasuredflowRecord> CONSTRAINT_7 = createUniqueKey(Measuredflow.MEASUREDFLOW, Measuredflow.MEASUREDFLOW.DATE, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_IDMEASURINGPOINT, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING);
		public static final UniqueKey<ChlorinecalculationRecord> CONSTRAINT_E = createUniqueKey(Chlorinecalculation.CHLORINECALCULATION, Chlorinecalculation.CHLORINECALCULATION.DATE, Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY, Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_IDWATERSYSTEM, Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<CommunityRecord, SubbasinRecord> FK_COMMUNITY_SUBBASIN1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_B, Community.COMMUNITY, Community.COMMUNITY.SUBBASIN_IDSUBBASIN);
		public static final ForeignKey<WatersystemRecord, CommunityRecord> FK_WATERSYSTEM_COMMUNITY1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_4, Watersystem.WATERSYSTEM, Watersystem.WATERSYSTEM.COMMUNITY_IDCOMMUNITY, Watersystem.WATERSYSTEM.COMMUNITY_SUBBASIN_IDSUBBASIN);
		public static final ForeignKey<WatersystemHasWaterspringRecord, WatersystemRecord> FK_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_C, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_IDWATERSYSTEM, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_IDCOMMUNITY, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN);
		public static final ForeignKey<WatersystemHasWaterspringRecord, WaterspringRecord> FK_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_CA, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING, WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING.WATERSPRING_IDWATERSPRING);
		public static final ForeignKey<MeasuringpointRecord, WatersystemHasWaterspringRecord> FK_MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_2, Measuringpoint.MEASURINGPOINT, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN, Measuringpoint.MEASURINGPOINT.WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING);
		public static final ForeignKey<MeasuredflowRecord, MeasuringpointRecord> FK_MEASUREDFLOW_MEASURINGPOINT1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_48, Measuredflow.MEASUREDFLOW, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_IDMEASURINGPOINT, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_IDWATERSYSTEM, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_IDCOMMUNITY, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN, Measuredflow.MEASUREDFLOW.MEASURINGPOINT_WATERSYSTEM_HAS_WATERSPRING_WATERSPRING_IDWATERSPRING);
		public static final ForeignKey<ChlorinecalculationRecord, WatersystemRecord> FK_CHLORINECALCULATION_WATERSYSTEM1 = createForeignKey(org.ongawa.peru.chlorination.persistence.db.jooq.Keys.CONSTRAINT_C, Chlorinecalculation.CHLORINECALCULATION, Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_IDWATERSYSTEM, Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_IDCOMMUNITY, Chlorinecalculation.CHLORINECALCULATION.WATERSYSTEM_COMMUNITY_SUBBASIN_IDSUBBASIN);
	}
}
