/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Chlorinecalculation;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Community;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Cubicreservoir;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Cubicreservoirdesinfection;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuredflow;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuringpoint;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Pipe;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Pipedesinfection;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Reliefvalve;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Reliefvalvedesinfection;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Subbasin;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Waterspring;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Watersystem;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.WatersystemHasWaterspring;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = 54249637;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_00ED8DC9_74E2_4313_9B53_00BE94A2E2F2,
			Sequences.SYSTEM_SEQUENCE_1C272693_3780_4363_8279_79B3AECC4A42,
			Sequences.SYSTEM_SEQUENCE_387E22AB_24F2_4072_866A_F16C4A74FAC0,
			Sequences.SYSTEM_SEQUENCE_4C3BB443_FC8B_4773_A6F3_1234A38140C5,
			Sequences.SYSTEM_SEQUENCE_67BA5D32_536C_4D1A_B05C_698E3E69C253,
			Sequences.SYSTEM_SEQUENCE_80D4B0E6_D08E_4BCC_BD05_91BD2381C466,
			Sequences.SYSTEM_SEQUENCE_97AF17BE_B1A5_4B94_886D_8855013F364B,
			Sequences.SYSTEM_SEQUENCE_EEEE937E_FB9E_414B_BB8B_B2DC440D80D5);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Subbasin.SUBBASIN,
			Community.COMMUNITY,
			Watersystem.WATERSYSTEM,
			Waterspring.WATERSPRING,
			WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING,
			Measuringpoint.MEASURINGPOINT,
			Measuredflow.MEASUREDFLOW,
			Chlorinecalculation.CHLORINECALCULATION,
			Cubicreservoir.CUBICRESERVOIR,
			Pipe.PIPE,
			Reliefvalve.RELIEFVALVE,
			Cubicreservoirdesinfection.CUBICRESERVOIRDESINFECTION,
			Pipedesinfection.PIPEDESINFECTION,
			Reliefvalvedesinfection.RELIEFVALVEDESINFECTION);
	}
}
