/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_23AE777B_5C1C_48BF_A322_E918F2A821BF</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_23AE777B_5C1C_48BF_A322_E918F2A821BF = new SequenceImpl<Long>("SYSTEM_SEQUENCE_23AE777B_5C1C_48BF_A322_E918F2A821BF", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2ACD442C_83AB_457C_9F14_0FB4458E951F</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2ACD442C_83AB_457C_9F14_0FB4458E951F = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2ACD442C_83AB_457C_9F14_0FB4458E951F", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2C778BF5_57C1_424E_9B22_8AC5C2FDB6CA</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2C778BF5_57C1_424E_9B22_8AC5C2FDB6CA = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2C778BF5_57C1_424E_9B22_8AC5C2FDB6CA", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_308B1B80_D8AF_4259_94D0_1B6973E663A6</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_308B1B80_D8AF_4259_94D0_1B6973E663A6 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_308B1B80_D8AF_4259_94D0_1B6973E663A6", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_371DE259_0742_42ED_8B0C_DF313B67F136</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_371DE259_0742_42ED_8B0C_DF313B67F136 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_371DE259_0742_42ED_8B0C_DF313B67F136", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_5A2D812F_D11C_44F4_A5E3_4B6F168FE26B</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_5A2D812F_D11C_44F4_A5E3_4B6F168FE26B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_5A2D812F_D11C_44F4_A5E3_4B6F168FE26B", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_6C2DE702_9E17_4518_86A6_739E87E7EF2C</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_6C2DE702_9E17_4518_86A6_739E87E7EF2C = new SequenceImpl<Long>("SYSTEM_SEQUENCE_6C2DE702_9E17_4518_86A6_739E87E7EF2C", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_76BFC7EF_5E47_4248_B446_15ECBFB7E0FD</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_76BFC7EF_5E47_4248_B446_15ECBFB7E0FD = new SequenceImpl<Long>("SYSTEM_SEQUENCE_76BFC7EF_5E47_4248_B446_15ECBFB7E0FD", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_C52CBFB9_67E1_4257_9417_F87B455C1C94</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_C52CBFB9_67E1_4257_9417_F87B455C1C94 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_C52CBFB9_67E1_4257_9417_F87B455C1C94", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_DEAA65DD_32F2_4937_AB89_16384153507B</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_DEAA65DD_32F2_4937_AB89_16384153507B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_DEAA65DD_32F2_4937_AB89_16384153507B", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
