/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1BC00EBE_2282_4082_92EC_0F4966C3FE45</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_1BC00EBE_2282_4082_92EC_0F4966C3FE45 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1BC00EBE_2282_4082_92EC_0F4966C3FE45", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2EE34411_6E17_4CCE_86F4_463A17435FF3</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2EE34411_6E17_4CCE_86F4_463A17435FF3 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2EE34411_6E17_4CCE_86F4_463A17435FF3", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_35FF4A37_4EE4_4C9C_A3A5_C790097BDEF1</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_35FF4A37_4EE4_4C9C_A3A5_C790097BDEF1 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_35FF4A37_4EE4_4C9C_A3A5_C790097BDEF1", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_398F4447_9E45_4D24_9555_9D46148EFF70</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_398F4447_9E45_4D24_9555_9D46148EFF70 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_398F4447_9E45_4D24_9555_9D46148EFF70", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_3E5CAD45_8F90_4E21_B210_A28E46B05BF1</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_3E5CAD45_8F90_4E21_B210_A28E46B05BF1 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_3E5CAD45_8F90_4E21_B210_A28E46B05BF1", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_6941A1D1_6594_44C2_8595_03222C4CD061</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_6941A1D1_6594_44C2_8595_03222C4CD061 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_6941A1D1_6594_44C2_8595_03222C4CD061", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_E0AD7B0E_5187_47AC_BF8A_C373F03C9EC4</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_E0AD7B0E_5187_47AC_BF8A_C373F03C9EC4 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_E0AD7B0E_5187_47AC_BF8A_C373F03C9EC4", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_FCB1C4CF_B302_4717_96C1_A2454F482B3E</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_FCB1C4CF_B302_4717_96C1_A2454F482B3E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_FCB1C4CF_B302_4717_96C1_A2454F482B3E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
