/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_0DCBAB1F_4B5A_41B1_9A54_41B5BAAD3477</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_0DCBAB1F_4B5A_41B1_9A54_41B5BAAD3477 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_0DCBAB1F_4B5A_41B1_9A54_41B5BAAD3477", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2E144B2F_C509_44D4_AF51_12FD446444EF</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2E144B2F_C509_44D4_AF51_12FD446444EF = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2E144B2F_C509_44D4_AF51_12FD446444EF", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_4DB32937_93F1_4362_8A5F_C4F95EBD8CAD</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_4DB32937_93F1_4362_8A5F_C4F95EBD8CAD = new SequenceImpl<Long>("SYSTEM_SEQUENCE_4DB32937_93F1_4362_8A5F_C4F95EBD8CAD", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_715FB6FF_7F5C_4126_8F64_8B8D39A7BCEE</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_715FB6FF_7F5C_4126_8F64_8B8D39A7BCEE = new SequenceImpl<Long>("SYSTEM_SEQUENCE_715FB6FF_7F5C_4126_8F64_8B8D39A7BCEE", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_8F8999BA_7242_461E_A2F0_82D268F6E5AA</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_8F8999BA_7242_461E_A2F0_82D268F6E5AA = new SequenceImpl<Long>("SYSTEM_SEQUENCE_8F8999BA_7242_461E_A2F0_82D268F6E5AA", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_AB7EC66E_31A4_4398_9FA4_DF2EFC601005</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_AB7EC66E_31A4_4398_9FA4_DF2EFC601005 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_AB7EC66E_31A4_4398_9FA4_DF2EFC601005", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_EE51FDD7_606F_47EA_BB94_E4EE53EBD082</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_EE51FDD7_606F_47EA_BB94_E4EE53EBD082 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_EE51FDD7_606F_47EA_BB94_E4EE53EBD082", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_F7EF39F7_73F4_4A2E_88DC_E706C6A48CDD</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_F7EF39F7_73F4_4A2E_88DC_E706C6A48CDD = new SequenceImpl<Long>("SYSTEM_SEQUENCE_F7EF39F7_73F4_4A2E_88DC_E706C6A48CDD", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}