/**
 * This class is generated by jOOQ
 */
package org.ongawa.peru.chlorination.persistence.db.jooq;


import javax.annotation.Generated;

import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Chlorinecalculation;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Community;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Cubicreservoir;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuredflow;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuringpoint;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Pipe;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Reliefvalve;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Subbasin;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Waterspring;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.Watersystem;
import org.ongawa.peru.chlorination.persistence.db.jooq.tables.WatersystemHasWaterspring;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.SUBBASIN
	 */
	public static final Subbasin SUBBASIN = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Subbasin.SUBBASIN;

	/**
	 * The table PUBLIC.COMMUNITY
	 */
	public static final Community COMMUNITY = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Community.COMMUNITY;

	/**
	 * The table PUBLIC.WATERSYSTEM
	 */
	public static final Watersystem WATERSYSTEM = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Watersystem.WATERSYSTEM;

	/**
	 * The table PUBLIC.WATERSPRING
	 */
	public static final Waterspring WATERSPRING = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Waterspring.WATERSPRING;

	/**
	 * The table PUBLIC.WATERSYSTEM_HAS_WATERSPRING
	 */
	public static final WatersystemHasWaterspring WATERSYSTEM_HAS_WATERSPRING = org.ongawa.peru.chlorination.persistence.db.jooq.tables.WatersystemHasWaterspring.WATERSYSTEM_HAS_WATERSPRING;

	/**
	 * The table PUBLIC.MEASURINGPOINT
	 */
	public static final Measuringpoint MEASURINGPOINT = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuringpoint.MEASURINGPOINT;

	/**
	 * The table PUBLIC.MEASUREDFLOW
	 */
	public static final Measuredflow MEASUREDFLOW = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Measuredflow.MEASUREDFLOW;

	/**
	 * The table PUBLIC.CHLORINECALCULATION
	 */
	public static final Chlorinecalculation CHLORINECALCULATION = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Chlorinecalculation.CHLORINECALCULATION;

	/**
	 * The table PUBLIC.CUBICRESERVOIR
	 */
	public static final Cubicreservoir CUBICRESERVOIR = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Cubicreservoir.CUBICRESERVOIR;

	/**
	 * The table PUBLIC.PIPE
	 */
	public static final Pipe PIPE = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Pipe.PIPE;

	/**
	 * The table PUBLIC.RELIEFVALVE
	 */
	public static final Reliefvalve RELIEFVALVE = org.ongawa.peru.chlorination.persistence.db.jooq.tables.Reliefvalve.RELIEFVALVE;
}